version: "3.2"

volumes:
  node_data:
  client_data:

services:
 tezosnode:
    image: tezos/tezos:mainnet
    hostname: tezosnode
    command: tezos-node --net-addr :9732
    ports:
      - "9732:9732"
      - "8732:8732"
    expose:
      - "8732"
    volumes:
    volumes:
      - node_data:/var/run/tezos/node
      - client_data:/var/run/tezos/client
    restart: on-failure
    networks:
      - scrapers-network

 xtz:
    build:
      context: ../../../..
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-xtz
    image: ${DOCKER_HUB_LOGIN}/xtz
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

networks:
  scrapers-network:
