version: '3.2'
services:
  
  mastermerkle:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-masterMerkle
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_mastermerkle:latest
    networks:
      - kafka-network
      - redis-network
      - influxdb-network
    environment:
      - EXEC_MODE=production
    logging:
      options:
        max-size: "50m"

networks:
  kafka-network:
    external:
        name: kafka_kafka-network
  redis-network:
    external:
        name: redis_redis-network
  influxdb-network:
    external:
        name: influxdb_influxdb-network
